#!/bin/bash
set -e

echo "==> Setting up C++ Build Environment for Trading Core..."

# Check if Conan is installed
if ! command -v conan &> /dev/null; then
    echo "==> Conan not found. Installing via pip3..."
    pip3 install conan
fi

echo "==> Creating default Conan profile if it doesn't exist..."
conan profile detect --force || true

# Install dependencies using Conan
echo "==> Installing dependencies via Conan..."
mkdir -p build
cd build
conan install .. --build=missing

# Configure and Build using CMake
echo "==> Configuring CMake..."
# We use the CMake toolchain generated by Conan
cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release

echo "==> Building trading-core..."
cmake --build . --config Release

echo "==> Build successful! Executable is at build/trading-core"
